export enum ContentActions {
  LIST_HIGHEST_RATED_CONTENT = "LIST_HIGHEST_RATED_CONTENT",
  LIST_MOST_POPULAR_CONTENT = "LIST_MOST_POPULAR_CONTENT",
  CLEAR_STATE = "CLEAR_STATE",
  SEARCH_CONTENT = "SEARCH_CONTENT",
  LOAD_SECTION = "LOAD_SECTION",
}
